"
your sieve_of_erasthasthanes.py IS REALLY GOOD 

Seeing that matrix of 4 digit prime numbers going on 
continously was soo nice so :-


--------------------------------------------------------

Make a terminal project that can generate n-digit prime
number and run it for set number of seconds



primeshow -5 --2m  (-100)



this should be the command and we can pass arguments
5  ==> all 5 digit prime number
2m ==> loops for 2 minutes 
100 => (if that isn't possible loop 100 times) 




do it in RUST or shell script or zsh etc
"

